# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='title',
        ),
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
