# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
